// lib/copy/traderIdentity.ts
//
// Shared identity helpers for copy-trading trader display.
// Read-only utilities — no API calls, no side effects.

/** Shortened wallet address for display: 0x2005d1…7875ea */
export function shortenWallet(addr: string): string {
  if (!addr || addr.length < 14) return addr;
  return `${addr.slice(0, 8)}…${addr.slice(-6)}`;
}

/**
 * Returns true when a stored bot/wallet name is autogenerated or meaningless:
 *   - null / blank
 *   - exact wallet address  (0x…)
 *   - shortened wallet      (0x1234…abcd)
 *   - "Paper — 0x…"  (address-only Paper prefix — not a real name)
 *
 * Preserves:
 *   - "RN1", "cryptotrader", "Paper — RN1", any non-address human name
 */
export function isAutoGeneratedName(
  name: string | null | undefined,
  walletAddress?: string | null,
): boolean {
  if (!name) return true;
  const n = name.trim();
  if (!n) return true;

  // Generic placeholder
  if (n === 'Unknown Trader') return true;

  // Exact address match
  if (walletAddress && n.toLowerCase() === walletAddress.toLowerCase()) return true;

  // Full hex address: 0x + at least 8 hex chars
  if (/^0x[0-9a-fA-F]{8,}$/.test(n)) return true;

  // Shortened hex address: 0x1234[…./][abcd]
  if (/^0x[0-9a-fA-F]{4,8}[…\.]+[0-9a-fA-F]{4,8}$/i.test(n)) return true;

  // "Paper — 0x…"  (only when followed by 0x address, not a real name)
  if (/^Paper\s*[—\-]\s*0x[0-9a-fA-F]/i.test(n)) return true;

  return false;
}

/**
 * Resolves the best human-readable trader name to display.
 *
 * Priority:
 *  1. displayName  — when non-null and not autogenerated
 *  2. "Unknown Trader" — when no walletAddress either
 *  3. Shortened wallet — as a last-resort readable label
 */
export function resolveTraderName(
  displayName: string | null | undefined,
  walletAddress: string | null | undefined,
): string {
  if (displayName && !isAutoGeneratedName(displayName, walletAddress)) return displayName;
  if (walletAddress) return shortenWallet(walletAddress);
  return 'Unknown Trader';
}
