// GET  /api/copy/add-paper-bot?wallet=0x...        — audit only (no writes)
// POST /api/copy/add-paper-bot                      — safe upsert / create
//
// Creates or restores a single PAPER copy bot for one wallet.
//
// Rules:
//   - NEVER enables a bot automatically (is_enabled always false on creation)
//   - NEVER creates LIVE bots
//   - NEVER enables ARM LIVE
//   - NEVER touches existing open positions, attempts, or trading execution
//   - Upserts tracked_wallets (case-insensitive wallet match)
//   - Creates or updates copy_bots (case-insensitive wallet match)
//   - Name is only overwritten when current value is blank or autogenerated
//   - sizing_value and max_trade_size are always set to the supplied values

import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { isAutoGeneratedName } from '@/lib/copy/traderIdentity';

export const dynamic   = 'force-dynamic';
export const revalidate = 0;

const NO_CACHE = { 'Cache-Control': 'no-store, max-age=0' };

const DEFAULT_SIZING = 0.10;

function getServiceClient() {
  let url = (process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || '').trim();
  const key = (process.env.SUPABASE_SERVICE_ROLE_KEY || '').trim();
  if (url.startsWith('$')) url = '';
  if (!url.startsWith('http') || !key) return null;
  return createClient(url, key, { auth: { persistSession: false } });
}

// ─── GET — audit ──────────────────────────────────────────────────────────────

export async function GET(request: Request) {
  const client = getServiceClient();
  if (!client) {
    return NextResponse.json({ ok: false, error: 'Supabase credentials missing' }, { status: 500, headers: NO_CACHE });
  }

  const { searchParams } = new URL(request.url);
  const wallet = searchParams.get('wallet')?.trim();
  if (!wallet || !wallet.startsWith('0x')) {
    return NextResponse.json({ ok: false, error: 'wallet query parameter required (0x…)' }, { status: 400, headers: NO_CACHE });
  }

  try {
    const [walletRes, botRes] = await Promise.all([
      client.from('tracked_wallets').select('wallet_address, display_name, is_active, created_at').ilike('wallet_address', wallet),
      client.from('copy_bots').select('id, name, wallet_address, is_enabled, mode, arm_live, opens_only, copy_closes, copy_mode, sizing_value, max_trade_size').ilike('wallet_address', wallet),
    ]);

    const walletRow = (walletRes.data ?? [])[0] ?? null;
    const botRow    = (botRes.data   ?? [])[0] ?? null;

    return NextResponse.json({
      ok: true,
      wallet_address: wallet,
      tracked_wallet: walletRow
        ? { found: true, display_name: walletRow.display_name, is_active: walletRow.is_active, created_at: walletRow.created_at }
        : { found: false },
      copy_bot: botRow
        ? { found: true, id: botRow.id, name: botRow.name, is_enabled: botRow.is_enabled, mode: botRow.mode, arm_live: botRow.arm_live, opens_only: botRow.opens_only, copy_closes: botRow.copy_closes, copy_mode: botRow.copy_mode, sizing_value: botRow.sizing_value, max_trade_size: botRow.max_trade_size }
        : { found: false },
    }, { headers: NO_CACHE });
  } catch (err) {
    return NextResponse.json({ ok: false, error: err instanceof Error ? err.message : 'Unknown error' }, { status: 500, headers: NO_CACHE });
  }
}

// ─── POST — upsert / create ───────────────────────────────────────────────────

export async function POST(request: Request) {
  const client = getServiceClient();
  if (!client) {
    return NextResponse.json({ ok: false, error: 'Supabase credentials missing' }, { status: 500, headers: NO_CACHE });
  }

  let body: Record<string, unknown>;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ ok: false, error: 'Invalid JSON body' }, { status: 400, headers: NO_CACHE });
  }

  const wallet_address = typeof body.wallet_address === 'string' ? body.wallet_address.trim() : '';
  if (!wallet_address || !wallet_address.startsWith('0x') || wallet_address.length < 10) {
    return NextResponse.json({ ok: false, error: 'wallet_address is required (0x…)' }, { status: 400, headers: NO_CACHE });
  }

  const display_name  = typeof body.display_name  === 'string' ? body.display_name.trim()  || null : null;
  const sizing_value  = typeof body.sizing_value  === 'number' && body.sizing_value  > 0 ? body.sizing_value  : DEFAULT_SIZING;
  const max_trade_size = typeof body.max_trade_size === 'number' && body.max_trade_size > 0 ? body.max_trade_size : DEFAULT_SIZING;

  const now = new Date().toISOString();

  try {
    // ── 1. Lookup existing tracked_wallet (case-insensitive) ─────────────────
    const { data: existingWallets } = await client
      .from('tracked_wallets')
      .select('wallet_address, display_name, is_active')
      .ilike('wallet_address', wallet_address);

    const existingWallet = (existingWallets ?? [])[0] ?? null;
    let wallet_action: string;

    if (!existingWallet) {
      // Create new tracked_wallet
      const { error: wErr } = await client.from('tracked_wallets').insert({
        wallet_address,
        display_name,
        is_active: true,
        source: 'POLYMARKET_DISCOVER',
        created_at: now,
        updated_at: now,
      });
      if (wErr) {
        return NextResponse.json({ ok: false, error: `Failed to create tracked wallet: ${wErr.message}`, step: 'create_wallet' }, { status: 500, headers: NO_CACHE });
      }
      wallet_action = 'created';
    } else {
      // Preserve existing; only update display_name if autogenerated
      if (display_name && isAutoGeneratedName(existingWallet.display_name, existingWallet.wallet_address)) {
        await client.from('tracked_wallets').update({ display_name, updated_at: now }).ilike('wallet_address', wallet_address);
        wallet_action = 'updated_name';
      } else {
        wallet_action = 'preserved';
      }
    }

    // ── 2. Lookup existing copy_bot (case-insensitive) ───────────────────────
    const { data: existingBots } = await client
      .from('copy_bots')
      .select('id, name, is_enabled, mode, arm_live, opens_only, copy_closes, copy_mode, sizing_value, max_trade_size')
      .ilike('wallet_address', wallet_address);

    const existingBot = (existingBots ?? [])[0] ?? null;
    let bot_action: string;
    let finalBot: Record<string, unknown>;

    if (!existingBot) {
      // Create new PAPER bot — disabled initially
      const botName = display_name || (wallet_address.length > 14 ? `${wallet_address.slice(0, 8)}…${wallet_address.slice(-6)}` : wallet_address);
      const newBot = {
        name:               botName,
        wallet_address,
        mode:               'PAPER',
        is_enabled:         false,
        arm_live:           false,
        opens_only:         false,
        copy_closes:        true,
        copy_mode:          'exact',
        sizing_value,
        max_trade_size,
        max_open_positions: 0,
        max_trades_per_hour: 0,
        max_slippage:       0.03,
        delay_seconds:      0,
        created_at:         now,
        updated_at:         now,
      };

      const { data: created, error: bErr } = await client
        .from('copy_bots')
        .insert(newBot)
        .select('*')
        .single();

      if (bErr) {
        return NextResponse.json({ ok: false, error: `Failed to create copy bot: ${bErr.message}`, step: 'create_bot' }, { status: 500, headers: NO_CACHE });
      }
      bot_action = 'created';
      finalBot = created as Record<string, unknown>;
    } else {
      // Update existing bot: mode, arm_live, sizing — never change is_enabled
      const updates: Record<string, unknown> = {
        mode:          'PAPER',
        arm_live:      false,
        sizing_value,
        max_trade_size,
        updated_at:    now,
      };
      // Only update name if it's autogenerated
      if (display_name && isAutoGeneratedName(existingBot.name, wallet_address)) {
        updates.name = display_name;
      }

      const { data: updated, error: uErr } = await client
        .from('copy_bots')
        .update(updates)
        .eq('id', existingBot.id)
        .select('*')
        .single();

      if (uErr) {
        return NextResponse.json({ ok: false, error: `Failed to update copy bot: ${uErr.message}`, step: 'update_bot' }, { status: 500, headers: NO_CACHE });
      }
      bot_action = 'updated';
      finalBot = updated as Record<string, unknown>;
    }

    console.info(
      `ADD_PAPER_BOT wallet=${wallet_address.slice(0, 10)}… wallet_action=${wallet_action} bot_action=${bot_action} ` +
      `sizing=${sizing_value} max=${max_trade_size} is_enabled=${finalBot.is_enabled ?? false}`
    );

    return NextResponse.json({
      ok:             true,
      wallet_action,
      bot_action,
      bot: {
        id:             finalBot.id,
        name:           finalBot.name,
        wallet_address: finalBot.wallet_address,
        is_enabled:     finalBot.is_enabled,
        mode:           finalBot.mode,
        arm_live:       finalBot.arm_live,
        opens_only:     finalBot.opens_only,
        copy_closes:    finalBot.copy_closes,
        copy_mode:      finalBot.copy_mode,
        sizing_value:   finalBot.sizing_value,
        max_trade_size: finalBot.max_trade_size,
      },
    }, { headers: NO_CACHE });

  } catch (err) {
    return NextResponse.json({ ok: false, error: err instanceof Error ? err.message : 'Unknown error' }, { status: 500, headers: NO_CACHE });
  }
}
