// POST /api/copy/sync-trader-names
//
// Read-only scrape of the Polymarket Daily / Weekly / Monthly leaderboards,
// then update ONLY the name fields of existing tracked_wallets and copy_bots.
//
// NEVER creates new wallets or bots.
// NEVER changes is_enabled, arm_live, mode, opens_only, copy_closes, sizing, or any
// trading field.
// NEVER touches open positions, attempts, or historical records.
// Only writes to display_name (tracked_wallets) and name (copy_bots) when the current
// value is missing or autogenerated.

import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { isAutoGeneratedName } from '@/lib/copy/traderIdentity';

export const dynamic   = 'force-dynamic';
export const revalidate = 0;

const NO_CACHE     = { 'Cache-Control': 'no-store, max-age=0' };
const LB_ENDPOINT  = 'https://data-api.polymarket.com/v1/leaderboard';

function getServiceClient() {
  let url = (process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || '').trim();
  const key = (process.env.SUPABASE_SERVICE_ROLE_KEY || '').trim();
  if (url.startsWith('$')) url = '';
  if (!url.startsWith('http') || !key) return null;
  return createClient(url, key, { auth: { persistSession: false } });
}

// ─── Leaderboard fetch ────────────────────────────────────────────────────────

type LbEntry = { addr: string; name: string | null; username: string | null };

async function fetchLeaderboard(timePeriod: string): Promise<LbEntry[]> {
  const url = new URL(LB_ENDPOINT);
  url.searchParams.set('category', 'OVERALL');
  url.searchParams.set('timePeriod', timePeriod);
  url.searchParams.set('orderBy', 'PNL');
  url.searchParams.set('limit', '50');
  url.searchParams.set('offset', '0');

  const res = await fetch(url.toString(), {
    signal:  AbortSignal.timeout(8_000),
    headers: { Accept: 'application/json', 'User-Agent': 'btcbot/1.0' },
    cache:   'no-store',
  });

  if (!res.ok) return [];

  const json = await res.json() as unknown;
  const items: Record<string, unknown>[] = Array.isArray(json)
    ? json as Record<string, unknown>[]
    : ((json as Record<string, unknown>).data
       ?? (json as Record<string, unknown>).results
       ?? (json as Record<string, unknown>).traders
       ?? []) as Record<string, unknown>[];

  return items
    .map((e) => {
      const addr = typeof e.proxyWallet === 'string' ? e.proxyWallet.trim() : null;
      if (!addr) return null;
      const name     = typeof e.userName    === 'string' ? e.userName.trim()    || null : null;
      const username = typeof e.xUsername   === 'string' ? e.xUsername.trim()   || null : null;
      return { addr, name, username };
    })
    .filter((r): r is LbEntry => r !== null);
}

// ─── Main handler ─────────────────────────────────────────────────────────────

export async function POST() {
  const client = getServiceClient();
  if (!client) {
    return NextResponse.json({ ok: false, error: 'Supabase credentials missing' }, { status: 500, headers: NO_CACHE });
  }

  const now = new Date().toISOString();

  try {
    // ── 1. Fetch all three leaderboards in parallel ────────────────────────────
    const [daily, weekly, monthly] = await Promise.all([
      fetchLeaderboard('DAY'),
      fetchLeaderboard('WEEK'),
      fetchLeaderboard('MONTH'),
    ]);

    // ── 2. Build wallet → best name map (lower-case keys) ─────────────────────
    // Priority: display_name (userName) preferred; username (xUsername) as fallback.
    // Earlier periods (monthly) win when multiple entries conflict.
    const nameMap = new Map<string, { name: string; username: string | null }>();

    for (const entry of [...monthly, ...weekly, ...daily]) {
      const key = entry.addr.toLowerCase();
      if (!nameMap.has(key) && (entry.name || entry.username)) {
        nameMap.set(key, {
          name:     entry.name ?? entry.username ?? '',
          username: entry.username,
        });
      }
    }

    const leaderboardNamesFound = nameMap.size;

    // ── 3. Fetch all tracked wallets ───────────────────────────────────────────
    const { data: wallets, error: wErr } = await client
      .from('tracked_wallets')
      .select('wallet_address, display_name');

    if (wErr) {
      return NextResponse.json({ ok: false, error: wErr.message, step: 'fetch_wallets' }, { status: 500, headers: NO_CACHE });
    }

    const trackedWallets = (wallets ?? []) as { wallet_address: string; display_name: string | null }[];
    const walletsChecked = trackedWallets.length;

    // ── 4. Fetch all copy bots ─────────────────────────────────────────────────
    const { data: bots, error: bErr } = await client
      .from('copy_bots')
      .select('id, wallet_address, name');

    if (bErr) {
      return NextResponse.json({ ok: false, error: bErr.message, step: 'fetch_bots' }, { status: 500, headers: NO_CACHE });
    }

    const allBots = (bots ?? []) as { id: string; wallet_address: string; name: string }[];

    // ── 5. Update tracked_wallets ──────────────────────────────────────────────
    let trackedWalletsUpdated = 0;
    let customNamesPreserved  = 0;
    const unmatchedWallets: string[] = [];

    for (const tw of trackedWallets) {
      const key    = tw.wallet_address.toLowerCase();
      const match  = nameMap.get(key);

      if (!match) {
        unmatchedWallets.push(tw.wallet_address);
        continue;
      }

      if (!isAutoGeneratedName(tw.display_name, tw.wallet_address)) {
        // Existing custom name — preserve it
        customNamesPreserved++;
        continue;
      }

      // Update: current value is blank/autogenerated
      const { error: upErr } = await client
        .from('tracked_wallets')
        .update({ display_name: match.name, updated_at: now })
        .eq('wallet_address', tw.wallet_address);

      if (!upErr) trackedWalletsUpdated++;
    }

    // ── 6. Update copy_bots names ──────────────────────────────────────────────
    let copyBotsUpdated = 0;

    for (const bot of allBots) {
      const key   = bot.wallet_address.toLowerCase();
      const match = nameMap.get(key);
      if (!match) continue;

      if (!isAutoGeneratedName(bot.name, bot.wallet_address)) continue; // custom name — keep

      const { error: upErr } = await client
        .from('copy_bots')
        .update({ name: match.name, updated_at: now })
        .eq('id', bot.id);

      if (!upErr) copyBotsUpdated++;
    }

    console.info(
      `SYNC_TRADER_NAMES wallets_checked=${walletsChecked} lb_found=${leaderboardNamesFound} ` +
      `wallets_updated=${trackedWalletsUpdated} bots_updated=${copyBotsUpdated} ` +
      `preserved=${customNamesPreserved} unmatched=${unmatchedWallets.length}`
    );

    return NextResponse.json({
      ok:                     true,
      wallets_checked:        walletsChecked,
      leaderboard_names_found: leaderboardNamesFound,
      tracked_wallets_updated: trackedWalletsUpdated,
      copy_bots_updated:       copyBotsUpdated,
      custom_names_preserved:  customNamesPreserved,
      unmatched_wallets:       unmatchedWallets.length,
      unmatched_addresses:     unmatchedWallets.slice(0, 20), // first 20 for UI display
    }, { headers: NO_CACHE });

  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    return NextResponse.json({ ok: false, error: message }, { status: 500, headers: NO_CACHE });
  }
}
