// POST /api/copy/sync-trader-names
//
// Comprehensive rename audit:
//   1. Fetches Polymarket leaderboards (DAY / WEEK / MONTH, + ALL if supported)
//   2. Builds a verified wallet-to-name map with conflict detection
//   3. Updates tracked_wallets.display_name and copy_bots.name ONLY when blank / autogenerated
//   4. Reports duplicates, conflicts, and unmatched wallets for manual review
//
// NEVER creates, deletes, or merges bots/wallets.
// NEVER changes is_enabled, arm_live, mode, opens_only, copy_closes, sizing, or any trading field.
// NEVER touches open positions, attempts, or historical records.

import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { isAutoGeneratedName } from '@/lib/copy/traderIdentity';

export const dynamic   = 'force-dynamic';
export const revalidate = 0;

const NO_CACHE    = { 'Cache-Control': 'no-store, max-age=0' };
const LB_ENDPOINT = 'https://data-api.polymarket.com/v1/leaderboard';

function getServiceClient() {
  let url = (process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || '').trim();
  const key = (process.env.SUPABASE_SERVICE_ROLE_KEY || '').trim();
  if (url.startsWith('$')) url = '';
  if (!url.startsWith('http') || !key) return null;
  return createClient(url, key, { auth: { persistSession: false } });
}

// ─── Leaderboard fetch ────────────────────────────────────────────────────────

type LbEntry = { addr: string; name: string | null; username: string | null; period: string };

async function fetchLeaderboard(timePeriod: string): Promise<LbEntry[]> {
  try {
    const url = new URL(LB_ENDPOINT);
    url.searchParams.set('category', 'OVERALL');
    url.searchParams.set('timePeriod', timePeriod);
    url.searchParams.set('orderBy', 'PNL');
    url.searchParams.set('limit', '100');
    url.searchParams.set('offset', '0');

    const res = await fetch(url.toString(), {
      signal:  AbortSignal.timeout(8_000),
      headers: { Accept: 'application/json', 'User-Agent': 'btcbot/1.0' },
      cache:   'no-store',
    });

    if (!res.ok) return [];

    const json = await res.json() as unknown;
    const items: Record<string, unknown>[] = Array.isArray(json)
      ? json as Record<string, unknown>[]
      : ((json as Record<string, unknown>).data
         ?? (json as Record<string, unknown>).results
         ?? (json as Record<string, unknown>).traders
         ?? []) as Record<string, unknown>[];

    return items
      .map((e) => {
        const addr = typeof e.proxyWallet === 'string' ? e.proxyWallet.trim() : null;
        if (!addr) return null;
        const name     = typeof e.userName  === 'string' ? e.userName.trim()  || null : null;
        const username = typeof e.xUsername === 'string' ? e.xUsername.trim() || null : null;
        return { addr, name, username, period: timePeriod };
      })
      .filter((r): r is LbEntry => r !== null);
  } catch {
    return [];
  }
}

// ─── Main handler ─────────────────────────────────────────────────────────────

type ManualReviewItem = {
  wallet_address:    string;
  current_bot_name:  string | null;
  current_wallet_name: string | null;
  reason:            string;
};

export async function POST() {
  const client = getServiceClient();
  if (!client) {
    return NextResponse.json({ ok: false, error: 'Supabase credentials missing' }, { status: 500, headers: NO_CACHE });
  }

  const now = new Date().toISOString();

  try {
    // ── 1. Fetch all leaderboard periods in parallel (ALL is optional) ─────────
    const [daily, weekly, monthly, allTime] = await Promise.all([
      fetchLeaderboard('DAY'),
      fetchLeaderboard('WEEK'),
      fetchLeaderboard('MONTH'),
      fetchLeaderboard('ALL'),   // graceful failure — returns [] if unsupported
    ]);

    // ── 2. Build per-wallet name collection (detect conflicts) ────────────────
    // Priority order: MONTH > WEEK > DAY > ALL  (iterate in reverse-priority order so higher priority overwrites)
    // A conflict is when the same wallet has DIFFERENT non-null display names across periods.

    // Step A: collect all distinct names per wallet across all periods
    type NameSet = Map<string, Set<string>>; // addr → set of distinct names seen
    const allNamesByWallet: NameSet = new Map();

    for (const entry of [...allTime, ...daily, ...weekly, ...monthly]) {
      if (!entry.name) continue;
      const key = entry.addr.toLowerCase();
      if (!allNamesByWallet.has(key)) allNamesByWallet.set(key, new Set());
      allNamesByWallet.get(key)!.add(entry.name);
    }

    // Step B: detect conflicts
    const conflictAddrs = new Set<string>();
    for (const [key, names] of allNamesByWallet) {
      if (names.size > 1) conflictAddrs.add(key);
    }

    // Step C: build final name map (monthly wins for conflicts — highest confidence)
    // Map: addr (lower) → { name, username }
    const nameMap = new Map<string, { name: string; username: string | null }>();

    // Iterate in ascending priority so higher-priority periods overwrite lower
    for (const entry of [...allTime, ...daily, ...weekly, ...monthly]) {
      const key = entry.addr.toLowerCase();
      if (entry.name && !nameMap.has(key)) {
        // First seen wins within the existing priority order; monthly iterates last
        // so we need the reverse — fill in allTime first, monthly last (overwrites)
      }
    }
    // Re-iterate in correct priority order (monthly = highest — do last)
    nameMap.clear();
    for (const entry of [...allTime, ...daily, ...weekly, ...monthly]) {
      const key = entry.addr.toLowerCase();
      if (entry.name) {
        // Always overwrite — monthly entries come last and have highest confidence
        nameMap.set(key, { name: entry.name, username: entry.username });
      }
    }

    const verifiedNamesFound = nameMap.size;

    // ── 3. Fetch all tracked_wallets ──────────────────────────────────────────
    const { data: wallets, error: wErr } = await client
      .from('tracked_wallets')
      .select('wallet_address, display_name');

    if (wErr) {
      return NextResponse.json({ ok: false, error: wErr.message, step: 'fetch_wallets' }, { status: 500, headers: NO_CACHE });
    }

    const trackedWallets = (wallets ?? []) as { wallet_address: string; display_name: string | null }[];
    const totalWalletsChecked = trackedWallets.length;

    // ── 4. Fetch all copy_bots ────────────────────────────────────────────────
    const { data: bots, error: bErr } = await client
      .from('copy_bots')
      .select('id, wallet_address, name');

    if (bErr) {
      return NextResponse.json({ ok: false, error: bErr.message, step: 'fetch_bots' }, { status: 500, headers: NO_CACHE });
    }

    const allBots = (bots ?? []) as { id: string; wallet_address: string; name: string | null }[];
    const totalBotsChecked = allBots.length;

    // ── 5. Detect duplicate bot wallet records ────────────────────────────────
    const botsByWallet = new Map<string, { id: string; name: string | null }[]>();
    for (const bot of allBots) {
      const key = bot.wallet_address.toLowerCase();
      if (!botsByWallet.has(key)) botsByWallet.set(key, []);
      botsByWallet.get(key)!.push({ id: bot.id, name: bot.name });
    }
    const duplicateWalletRecords = [...botsByWallet.entries()]
      .filter(([, v]) => v.length > 1)
      .map(([k]) => k);
    const duplicateWalletRecordsFound = duplicateWalletRecords.length;

    // ── 6. Build wallet display_name lookup (existing tracked_wallets) ─────────
    const trackedNameByWallet = new Map<string, string | null>();
    for (const tw of trackedWallets) {
      trackedNameByWallet.set(tw.wallet_address.toLowerCase(), tw.display_name);
    }

    // ── 7. Update tracked_wallets ─────────────────────────────────────────────
    let walletNamesUpdated   = 0;
    let customNamesPreserved = 0;
    const unmatchedWalletAddrs: string[] = [];
    const manualReview: ManualReviewItem[] = [];

    // Build bot name lookup for manual review
    const botNameByWallet = new Map<string, string | null>();
    for (const bot of allBots) {
      const key = bot.wallet_address.toLowerCase();
      if (!botNameByWallet.has(key)) botNameByWallet.set(key, bot.name);
    }

    for (const tw of trackedWallets) {
      const key   = tw.wallet_address.toLowerCase();
      const match = nameMap.get(key);

      if (!match) {
        unmatchedWalletAddrs.push(tw.wallet_address);
        // If tracked wallet has no leaderboard match, add to review only if name is also autogenerated
        if (isAutoGeneratedName(tw.display_name, tw.wallet_address)) {
          manualReview.push({
            wallet_address:      tw.wallet_address,
            current_bot_name:    botNameByWallet.get(key) ?? null,
            current_wallet_name: tw.display_name,
            reason:              'Not found on current leaderboards',
          });
        }
        continue;
      }

      // Conflict — add to review but still update if name is autogenerated (monthly wins)
      if (conflictAddrs.has(key)) {
        manualReview.push({
          wallet_address:      tw.wallet_address,
          current_bot_name:    botNameByWallet.get(key) ?? null,
          current_wallet_name: tw.display_name,
          reason:              `Conflicting names across leaderboard periods; applied: ${match.name}`,
        });
      }

      if (!isAutoGeneratedName(tw.display_name, tw.wallet_address)) {
        customNamesPreserved++;
        continue;
      }

      const { error: upErr } = await client
        .from('tracked_wallets')
        .update({ display_name: match.name, updated_at: now })
        .eq('wallet_address', tw.wallet_address);

      if (!upErr) walletNamesUpdated++;
    }

    // ── 8. Update copy_bots names ─────────────────────────────────────────────
    let botNamesUpdated = 0;

    for (const bot of allBots) {
      const key   = bot.wallet_address.toLowerCase();
      const match = nameMap.get(key);
      if (!match) continue;

      if (!isAutoGeneratedName(bot.name, bot.wallet_address)) continue; // custom — keep

      const { error: upErr } = await client
        .from('copy_bots')
        .update({ name: match.name, updated_at: now })
        .eq('id', bot.id);

      if (!upErr) botNamesUpdated++;
    }

    const unmatched = unmatchedWalletAddrs.length;
    const conflicts = conflictAddrs.size;

    console.info(
      `SYNC_TRADER_NAMES_FULL wallets=${totalWalletsChecked} bots=${totalBotsChecked} ` +
      `lb_found=${verifiedNamesFound} wallets_updated=${walletNamesUpdated} bots_updated=${botNamesUpdated} ` +
      `preserved=${customNamesPreserved} unmatched=${unmatched} conflicts=${conflicts} ` +
      `duplicates=${duplicateWalletRecordsFound}`
    );

    return NextResponse.json({
      ok:                          true,
      total_bots_checked:          totalBotsChecked,
      total_wallets_checked:       totalWalletsChecked,
      verified_names_found:        verifiedNamesFound,
      bot_names_updated:           botNamesUpdated,
      wallet_names_updated:        walletNamesUpdated,
      custom_names_preserved:      customNamesPreserved,
      unmatched_wallets:           unmatched,
      conflicting_wallets:         conflicts,
      duplicate_wallet_records_found: duplicateWalletRecordsFound,
      manual_review:               manualReview,       // full list for UI
      duplicate_wallet_records:    duplicateWalletRecords.slice(0, 10),
    }, { headers: NO_CACHE });

  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    return NextResponse.json({ ok: false, error: message }, { status: 500, headers: NO_CACHE });
  }
}
